export const miniBus = [
    {
        value:1,
        label:"مینی بوس آریان ایران خودرو دیزل",
        id:"itemFirst1"
    },
    {
        value:2,
        label:"مینی بوس ایسوز و ISUZU",
        id:"itemFirst2"
    },
    {
        value:3,
        label:"مینی بوس هیونداکروز ایران خودرو دیزل",
        id:"itemFirst3"
    },
]

// ***************************************************************second************************************************************

export const second = [
  {
    label: "مجموعه اگروز و متعلقات DPF(گروه 49 )",
    value: 1,
    id: "itemSecond1",
    idItem: "itemFirst1",
  },
  {
    label: "مجموعه بدنه و تزئینات (گروه)",
    value: 2,
    id: "itemSecond2",
    idItem: "itemFirst1",
  },
  {
    label: "مجموعه ترمز (گروه 42)",
    value: 3,
    id: "itemSecond3",
    idItem: "itemFirst1",
  },
  {
    label: "مجموعه شاسی (گروه 31)",
    value: 4,
    id: "itemSecond4",
    idItem: "itemFirst1",
  },
  {
    label: "مجموعه فرمان (گروه 46)",
    value: 5,
    id: "itemSecond5",
    idItem: "itemFirst1",
  },
  {
    label: "مجموعه گیربکس (گروه 26)",
    value: 6,
    id: "itemSecond6",
    idItem: "itemFirst1",
  },
  {
    label: "مجموعه موتور (گروه 24)",
    value: 7,
    id: "itemSecond7",
    idItem: "itemFirst1",
  },
  {
    label: "مجموعه اگروز و متعلقات DPF(گروه 49 )",
    value: 8,
    id: "itemSecond8",
    idItem: "itemFirst2",
  },
  {
    label: "مجموعه بدنه و تزئینات (گروه)",
    value: 9,
    id: "itemSecond9",
    idItem: "itemFirst2",
  },
  {
    label: "مجموعه ترمز (گروه 42)",
    value: 10,
    id: "itemSecond10",
    idItem: "itemFirst2",
  },
  {
    label: "مجموعه شاسی (گروه 31)",
    value: 11,
    id: "itemSecond11",
    idItem: "itemFirst2",
  },
  {
    label: "مجموعه فرمان (گروه 46)",
    value: 12,
    id: "itemSecond12",
    idItem: "itemFirst2",
  },
  {
    label: "مجموعه گیربکس (گروه 26)",
    value: 13,
    id: "itemSecond13",
    idItem: "itemFirst2",
  },
  {
    label: "مجموعه موتور (گروه 24)",
    value: 14,
    id: "itemSecond14",
    idItem: "itemFirst2",
  },
  {
    label: "مجموعه اگروز و متعلقات DPF(گروه 49 )",
    value: 15,
    id: "itemSecond15",
    idItem: "itemFirst3",
  },
  {
    label: "مجموعه بدنه و تزئینات (گروه)",
    value: 16,
    id: "itemSecond16",
    idItem: "itemFirst3",
  },
  {
    label: "مجموعه ترمز (گروه 42)",
    value: 17,
    id: "itemSecond17",
    idItem: "itemFirst3",
  },
  {
    label: "مجموعه شاسی (گروه 31)",
    value: 18,
    id: "itemSecond18",
    idItem: "itemFirst3",
  },
  {
    label: "مجموعه فرمان (گروه 46)",
    value: 19,
    id: "itemSecond19",
    idItem: "itemFirst3",
  },
  {
    label: "مجموعه گیربکس (گروه 26)",
    value: 20,
    id: "itemSecond20",
    idItem: "itemFirst3",
  },
  {
    label: "مجموعه موتور (گروه 24)",
    value: 21,
    id: "itemSecond21",
    idItem: "itemFirst3",
  },
  {
    label: "مجموعه اگروز و متعلقات DPF(گروه 49 )",
    value: 22,
    id: "itemSecond22",
    idItem: "itemFirst4",
  },
  {
    label: "مجموعه بدنه و تزئینات (گروه)",
    value: 23,
    id: "itemSecond23",
    idItem: "itemFirst4",
  },
  {
    label: "مجموعه ترمز(گروه 42)",
    value: 24,
    id: "itemSecond24",
    idItem: "itemFirst4",
  },
  {
    label: "مجموعه شاسی (گروه 31)",
    value: 25,
    id: "itemSecond25",
    idItem: "itemFirst4",
  },
  {
    label: "مجموعه فرمان (گروه 46)",
    value: 26,
    id: "itemSecond26",
    idItem: "itemFirst4",
  },
  {
    label: "مجموعه گیربکس (گروه 26)",
    value: 27,
    id: "itemSecond27",
    idItem: "itemFirst4",
  },
  {
    label: "مجموعه موتور (گروه 24)",
    value: 28,
    id: "itemSecond28",
    idItem: "itemFirst4",
  },

  {
    label: "مجموعه اگروز و متعلقات DPF(گروه 49 )",
    value: 29,
    id: "itemSecond29",
    idItem: "itemFirst5",
  },
  {
    label: "مجموعه بدنه و تزئینات (گروه)",
    value: 30,
    id: "itemSecond30",
    idItem: "itemFirst5",
  },
  {
    label: "مجموعه ترمز (گروه 42)",
    value: 31,
    id: "itemSecond31",
    idItem: "itemFirst5",
  },
  {
    label: "مجموعه شاسی (گروه 31)",
    value: 32,
    id: "itemSecond32",
    idItem: "itemFirst5",
  },
  {
    label: "مجموعه فرمان (گروه 46)",
    value: 33,
    id: "itemSecond33",
    idItem: "itemFirst5",
  },
  {
    label: "مجموعه گیربکس (گروه 26)",
    value: 34,
    id: "itemSecond34",
    idItem: "itemFirst5",
  },
  {
    label: "مجموعه موتور (گروه 24)",
    value: 35,
    id: "itemSecond35",
    idItem: "itemFirst5",
  },

  {
    label: "مجموعه اگروز و متعلقات DPF(گروه 49 )",
    value: 36,
    id: "itemSecond36",
    idItem: "itemFirst6",
  },
  {
    label: "مجموعه بدنه و تزئینات (گروه)",
    value: 37,
    id: "itemSecond37",
    idItem: "itemFirst6",
  },
  {
    label: "مجموعه ترمز (گروه 42)",
    value: 38,
    id: "itemSecond38",
    idItem: "itemFirst6",
  },
  {
    label: "مجموعه شاسی (گروه 31)",
    value: 39,
    id: "itemSecond39",
    idItem: "itemFirst6",
  },
  {
    label: "مجموعه فرمان (گروه 46)",
    value: 40,
    id: "itemSecond40",
    idItem: "itemFirst6",
  },
  {
    label: "مجموعه گیربکس (گروه 26)",
    value: 41,
    id: "itemSecond41",
    idItem: "itemFirst6",
  },
  {
    label: "مجموعه موتور (گروه 24)",
    value: 42,
    id: "itemSecond42",
    idItem: "itemFirst6",
  },

  {
    label: "مجموعه اگروز و متعلقات DPF(گروه 49 )",
    value: 43,
    id: "iteSecond43",
    idItem: "itemFirst7",
  },
  {
    label: "مجموعه بدنه و تزئینات (گروه)",
    value: 44,
    id: "itemSecond44",
    idItem: "itemFirst7",
  },
  {
    label: "مجموعه ترمز (گروه 42)",
    value: 45,
    id: "itemSecond45",
    idItem: "itemFirst7",
  },
  {
    label: "مجموعه شاسی (گروه 31)",
    value: 46,
    id: "itemSecond46",
    idItem: "itemFirst7",
  },
  {
    label: "مجموعه فرمان (گروه 46)",
    value: 47,
    id: "itemSecond47",
    idItem: "itemFirst7",
  },
  {
    label: "مجموعه گیربکس (گروه 26)",
    value: 48,
    id: "itemSecond48",
    idItem: "itemFirst7",
  },
  {
    label: "مجموعه موتور (گروه 24)",
    value: 49,
    id: "itemSecond49",
    idItem: "itemFirst7",
  },

  {
    label: "مجموعه اگروز و متعلقات DPF(گروه 49 )",
    value: 50,
    id: "itemSecond50",
    idItem: "itemFirst8",
  },
  {
    label: "مجموعه بدنه و تزئینات (گروه)",
    value: 51,
    id: "itemSecond51",
    idItem: "itemFirst8",
  },
  {
    label: "مجموعه ترمز (گروه 42)",
    value: 52,
    id: "itemSecond52",
    idItem: "itemFirst8",
  },
  {
    label: "مجموعه شاسی (گروه 31)",
    value: 53,
    id: "itemSecond53",
    idItem: "itemFirst8",
  },
  {
    label: "مجموعه فرمان (گروه 46)",
    value: 54,
    id: "itemSecond54",
    idItem: "itemFirst8",
  },
  {
    label: "مجموعه گیربکس (گروه 26)",
    value: 55,
    id: "itemSecond55",
    idItem: "itemFirst8",
  },
  {
    label: "مجموعه موتور (گروه 24)",
    value: 56,
    id: "itemSecond56",
    idItem: "itemFirst8",
  },
];

// ************************************************threee*****************************************************
export const three = [
  {
    label: "DPF و متعلقات",
    value: 1,
    id: "itemThree1",
    idItem: "itemSecond1",
  },
  {
    label: "SCR و متعلقات",
    value: 2,
    id: "itemThree2",
    idItem: "itemSecond1",
  },
  {
    label: "اگزوز",
    value: 3,
    id: "itemThree3",
    idItem: "itemSecond1",
  },
  {
    label: "مخازن و سوخت",
    value: 4,
    id: "itemThree4",
    idItem: "itemSecond1",
  },
  {
    label: "بیرون اتاق",
    value: 5,
    id: "itemThree5",
    idItem: "itemSecond2",
  },
  {
    label: "داخل اتاق",
    value: 6,
    id: "itemThree6",
    idItem: "itemSecond2",
  },
  {
    label: "قطعات منفصل بدنه",
    value: 7,
    id: "itemThree7",
    idItem: "itemSecond2",
  },
  {
    label: "الکترونیک ترمز",
    value: 8,
    id: "itemThree8",
    idItem: "itemSecond3",
  },
  {
    label: "مدار ترمز",
    value: 9,
    id: "itemThree9",
    idItem: "itemSecond3",
  },
  {
    label: "مکانیک ترمز",
    value: 10,
    id: "itemThree10",
    idItem: "itemSecond3",
  },
  {
    label: "رام ها و مجموعه قطعات شاسی",
    value: 11,
    id: "itemThree11",
    idItem: "itemSecond4",
  },
  {
    label: "متعلقات سیستم تعلیق",
    value: 12,
    id: "itemThree12",
    idItem: "itemSecond4",
  },
  {
    label: "جعبه فرمان",
    value: 13,
    id: "itemThree13",
    idItem: "itemSecond5",
  },
  {
    label: "ستون فرمان",
    value: 14,
    id: "itemThree14",
    idItem: "itemSecond5",
  },
  {
    label: "مدار هیدرولیک",
    value: 15,
    id: "itemThree15",
    idItem: "itemSecond5",
  },
  {
    label: "شیفتینگ",
    value: 16,
    id: "itemThree16",
    idItem: "itemSecond6",
  },
  {
    label: "گیربکس",
    value: 17,
    id: "itemThree17",
    idItem: "itemSecond6",
  },
  {
    label: "متعلقات گیربکس",
    value: 18,
    id: "itemThree18",
    idItem: "itemSecond6",
  },
  {
    label: "سیستم کولینگ",
    value: 19,
    id: "itemThree19",
    idItem: "itemSecond7",
  },
  {
    label: "فیلتراسیون",
    value: 20,
    id: "itemThree20",
    idItem: "itemSecond7",
  },
  {
    label: "متعلقات موتور",
    value: 21,
    id: "itemThree21",
    idItem: "itemSecond7",
  },
  {
    label: " موتور",
    value: 22,
    id: "itemThree22",
    idItem: "itemSecond7",
  },
  {
    label: "DPF و متعلقات",
    value: 23,
    id: "itemThree23",
    idItem: "itemSecond8",
  },
  {
    label: "SCR و متعلقات",
    value: 24,
    id: "itemThree24",
    idItem: "itemSecond8",
  },
  {
    label: "اگزوز",
    value: 25,
    id: "itemThree25",
    idItem: "itemSecond8",
  },
  {
    label: "مخازن و سوخت",
    value: 26,
    id: "itemThree26",
    idItem: "itemSecond8",
  },

  {
    label: "بیرون اتاق",
    value: 27,
    id: "itemThree27",
    idItem: "itemSecond9",
  },
  {
    label: "داخل اتاق",
    value: 28,
    id: "itemThree28",
    idItem: "itemSecond9",
  },
  {
    label: "قطعات منفصل بدنه",
    value: 29,
    id: "itemThree29",
    idItem: "itemSecond9",
  },
  {
    label: "الکترونیک ترمز",
    value: 811,
    id: "itemThree811",
    idItem: "itemSecond10",
  },
  {
    label: "مدار ترمز",
    value: 812,
    id: "itemThree812",
    idItem: "itemSecond10",
  },
  {
    label: "مکانیک ترمز",
    value: 813,
    id: "itemThree813",
    idItem: "itemSecond10",
  },
  {
    label: "رام ها و مجموعه قطعات شاسی",
    value: 30,
    id: "itemThree30",
    idItem: "itemSecond11",
  },
  {
    label: "متعلقات سیستم تعلیق",
    value: 31,
    id: "itemThree31",
    idItem: "itemSecond11",
  },

  {
    label: "جعبه فرمان",
    value: 32,
    id: "itemThree32",
    idItem: "itemSecond12",
  },
  {
    label: "ستون فرمان",
    value: 33,
    id: "itemThree33",
    idItem: "itemSecond12",
  },
  {
    label: "مدار هیدرولیک",
    value: 34,
    id: "itemThree35",
    idItem: "itemSecond12",
  },
  {
    label: "شیفتینگ",
    value: 35,
    id: "itemThree35",
    idItem: "itemSecond13",
  },
  {
    label: "گیربکس",
    value: 36,
    id: "itemThree35",
    idItem: "itemSecond13",
  },
  {
    label: "متعلقات گیربکس",
    value: 37,
    id: "itemThree37",
    idItem: "itemSecond13",
  },

  {
    label: "سیستم کولینگ",
    value: 38,
    id: "itemThree38",
    idItem: "itemSecond14",
  },
  {
    label: "فیلتراسیون",
    value: 39,
    id: "itemThree39",
    idItem: "itemSecond14",
  },
  {
    label: "متعلقات موتور",
    value: 40,
    id: "itemThree40",
    idItem: "itemSecond14",
  },
  {
    label: " موتور",
    value: 41,
    id: "itemThree41",
    idItem: "itemSecond14",
  },

  {
    label: "DPF و متعلقات",
    value: 42,
    id: "itemThree42",
    idItem: "itemSecond15",
  },
  {
    label: "SCR و متعلقات",
    value: 43,
    id: "itemThree43",
    idItem: "itemSecond15",
  },
  {
    label: "اگزوز",
    value: 44,
    id: "itemThree44",
    idItem: "itemSecond15",
  },
  {
    label: "مخازن و سوخت",
    value: 45,
    id: "itemThree45",
    idItem: "itemSecond15",
  },

  {
    label: "بیرون اتاق",
    value: 46,
    id: "itemThree46",
    idItem: "itemSecond16",
  },
  {
    label: "داخل اتاق",
    value: 47,
    id: "itemThree47",
    idItem: "itemSecond16",
  },
  {
    label: "قطعات منفصل بدنه",
    value: 48,
    id: "itemThree48",
    idItem: "itemSecond16",
  },
  {
    label: "الکترونیک ترمز",
    value: 814,
    id: "itemThree811",
    idItem: "itemSecond17",
  },
  {
    label: "مدار ترمز",
    value: 815,
    id: "itemThree812",
    idItem: "itemSecond17",
  },
  {
    label: "مکانیک ترمز",
    value: 816,
    id: "itemThree813",
    idItem: "itemSecond17",
  },
  {
    label: "رام ها و مجموعه قطعات شاسی",
    value: 49,
    id: "itemThree49",
    idItem: "itemSecond18",
  },
  {
    label: "متعلقات سیستم تعلیق",
    value: 50,
    id: "itemThree50",
    idItem: "itemSecond18",
  },
  {
    label: "جعبه فرمان",
    value: 51,
    id: "itemThree51",
    idItem: "itemSecond19",
  },
  {
    label: "ستون فرمان",
    value: 52,
    id: "itemThree52",
    idItem: "itemSecond19",
  },
  {
    label: "مدار هیدرولیک",
    value: 53,
    id: "itemThree53",
    idItem: "itemSecond19",
  },
  {
    label: "شیفتینگ",
    value: 54,
    id: "itemThree54",
    idItem: "itemSecond20",
  },
  {
    label: "گیربکس",
    value: 55,
    id: "itemThree55",
    idItem: "itemSecond20",
  },
  {
    label: "متعلقات گیربکس",
    value: 56,
    id: "itemThree56",
    idItem: "itemSecond20",
  },

  {
    label: "سیستم کولینگ",
    value: 57,
    id: "itemThree57",
    idItem: "itemSecond21",
  },
  {
    label: "فیلتراسیون",
    value: 59,
    id: "itemThree59",
    idItem: "itemSecond21",
  },
  {
    label: "متعلقات موتور",
    value: 60,
    id: "itemThree61",
    idItem: "itemSecond21",
  },
  {
    label: " موتور",
    value: 62,
    id: "itemThree62",
    idItem: "itemSecond21",
  },

  {
    label: "DPF و متعلقات",
    value: 63,
    id: "itemThree63",
    idItem: "itemSecond22",
  },
  {
    label: "SCR و متعلقات",
    value: 64,
    id: "itemThree64",
    idItem: "itemSecond22",
  },
  {
    label: "اگزوز",
    value: 65,
    id: "itemThree65",
    idItem: "itemSecond22",
  },
  {
    label: "مخازن و سوخت",
    value: 66,
    id: "itemThree66",
    idItem: "itemSecond22",
  },
  {
    label: "بیرون اتاق",
    value: 64,
    id: "itemThree67",
    idItem: "itemSecond23",
  },
  {
    label: "داخل اتاق",
    value: 68,
    id: "itemThree68",
    idItem: "itemSecond23",
  },
  {
    label: "قطعات منفصل بدنه",
    value: 69,
    id: "itemThree69",
    idItem: "itemSecond23",
  },
  {
    label: "الکترونیک ترمز",
    value: 817,
    id: "itemThree817",
    idItem: "itemSecond24",
  },
  {
    label: "مدار ترمز",
    value: 818,
    id: "itemThree818",
    idItem: "itemSecond24",
  },
  {
    label: "مکانیک ترمز",
    value: 819,
    id: "itemThree819",
    idItem: "itemSecond24",
  },
  {
    label: "رام ها و مجموعه قطعات شاسی",
    value: 70,
    id: "itemThree70",
    idItem: "itemSecond25",
  },
  {
    label: "متعلقات سیستم تعلیق",
    value: 71,
    id: "itemThree71",
    idItem: "itemSecond25",
  },
  {
    label: "جعبه فرمان",
    value: 72,
    id: "itemThree72",
    idItem: "itemSecond26",
  },
  {
    label: "ستون فرمان",
    value: 73,
    id: "itemThree73",
    idItem: "itemSecond26",
  },
  {
    label: "مدار هیدرولیک",
    value: 74,
    id: "itemThree74",
    idItem: "itemSecond26",
  },
  {
    label: "شیفتینگ",
    value: 75,
    id: "itemThree75",
    idItem: "itemSecond27",
  },
  {
    label: "گیربکس",
    value: 76,
    id: "itemThree76",
    idItem: "itemSecond27",
  },
  {
    label: "متعلقات گیربکس",
    value: 77,
    id: "itemThree77",
    idItem: "itemSecond27",
  },
  {
    label: "سیستم کولینگ",
    value: 78,
    id: "itemThree78",
    idItem: "itemSecond28",
  },
  {
    label: "فیلتراسیون",
    value: 79,
    id: "itemThree79",
    idItem: "itemSecond28",
  },
  {
    label: "متعلقات موتور",
    value: 80,
    id: "itemThree80",
    idItem: "itemSecond28",
  },
  {
    label: " موتور",
    value: 81,
    id: "itemThree81",
    idItem: "itemSecond28",
  },

  {
    label: "DPF و متعلقات",
    value: 82,
    id: "itemThree82",
    idItem: "itemSecond29",
  },
  {
    label: "SCR و متعلقات",
    value: 83,
    id: "itemThree83",
    idItem: "itemSecond29",
  },
  {
    label: "اگزوز",
    value: 84,
    id: "itemThree84",
    idItem: "itemSecond29",
  },
  {
    label: "مخازن و سوخت",
    value: 85,
    id: "itemThree85",
    idItem: "itemSecond29",
  },
  {
    label: "بیرون اتاق",
    value: 86,
    id: "itemThree86",
    idItem: "itemSecond30",
  },
  {
    label: "داخل اتاق",
    value: 87,
    id: "itemThree87",
    idItem: "itemSecond30",
  },
  {
    label: "قطعات منفصل بدنه",
    value: 88,
    id: "itemThree88",
    idItem: "itemSecond30",
  },

  {
    label: "الکترونیک ترمز",
    value: 89,
    id: "itemThree89",
    idItem: "itemSecond31",
  },
  {
    label: "مدار ترمز",
    value: 90,
    id: "itemThree90",
    idItem: "itemSecond31",
  },
  {
    label: "مکانیک ترمز",
    value: 91,
    id: "itemThree91",
    idItem: "itemSecond31",
  },
  {
    label: "رام ها و مجموعه قطعات شاسی",
    value: 92,
    id: "itemThree92",
    idItem: "itemSecond32",
  },
  {
    label: "متعلقات سیستم تعلیق",
    value: 93,
    id: "itemThree93",
    idItem: "itemSecond32",
  },
  {
    label: "جعبه فرمان",
    value: 94,
    id: "itemThree94",
    idItem: "itemSecond33",
  },
  {
    label: "ستون فرمان",
    value: 95,
    id: "itemThree95",
    idItem: "itemSecond33",
  },
  {
    label: "مدار هیدرولیک",
    value: 96,
    id: "itemThree96",
    idItem: "itemSecond33",
  },
  {
    label: "شیفتینگ",
    value: 97,
    id: "itemThree97",
    idItem: "itemSecond34",
  },
  {
    label: "گیربکس",
    value: 98,
    id: "itemThree98",
    idItem: "itemSecond34",
  },
  {
    label: "متعلقات گیربکس",
    value: 99,
    id: "itemThree99",
    idItem: "itemSecond34",
  },
  {
    label: "سیستم کولینگ",
    value: 100,
    id: "itemThree100",
    idItem: "itemSecond35",
  },
  {
    label: "فیلتراسیون",
    value: 101,
    id: "itemThree101",
    idItem: "itemSecond35",
  },
  {
    label: "متعلقات موتور",
    value: 102,
    id: "itemThree102",
    idItem: "itemSecond35",
  },
  {
    label: " موتور",
    value: 103,
    id: "itemThree103",
    idItem: "itemSecond35",
  },

  {
    label: "DPF و متعلقات",
    value: 104,
    id: "itemThree104",
    idItem: "itemSecond36",
  },
  {
    label: "SCR و متعلقات",
    value: 105,
    id: "itemThree105",
    idItem: "itemSecond36",
  },
  {
    label: "اگزوز",
    value: 106,
    id: "itemThree106",
    idItem: "itemSecond36",
  },
  {
    label: "مخازن و سوخت",
    value: 107,
    id: "itemThree107",
    idItem: "itemSecond36",
  },
  {
    label: "بیرون اتاق",
    value: 108,
    id: "itemThree108",
    idItem: "itemSecond37",
  },
  {
    label: "داخل اتاق",
    value: 109,
    id: "itemThree109",
    idItem: "itemSecond37",
  },
  {
    label: "قطعات منفصل بدنه",
    value: 110,
    id: "itemThree110",
    idItem: "itemSecond37",
  },
  {
    label: "الکترونیک ترمز",
    value: 111,
    id: "itemThree111",
    idItem: "itemSecond38",
  },
  {
    label: "مدار ترمز",
    value: 112,
    id: "itemThree112",
    idItem: "itemSecond38",
  },
  {
    label: "مکانیک ترمز",
    value: 113,
    id: "itemThree113",
    idItem: "itemSecond38",
  },
  {
    label: "رام ها و مجموعه قطعات شاسی",
    value: 114,
    id: "itemThree114",
    idItem: "itemSecond39",
  },
  {
    label: "متعلقات سیستم تعلیق",
    value: 115,
    id: "itemThree115",
    idItem: "itemSecond39",
  },
  {
    label: "جعبه فرمان",
    value: 116,
    id: "itemThree116",
    idItem: "itemSecond40",
  },
  {
    label: "ستون فرمان",
    value: 117,
    id: "itemThree117",
    idItem: "itemSecond40",
  },
  {
    label: "مدار هیدرولیک",
    value: 118,
    id: "itemThree118",
    idItem: "itemSecond40",
  },
  {
    label: "شیفتینگ",
    value: 119,
    id: "itemThree119",
    idItem: "itemSecond41",
  },
  {
    label: "گیربکس",
    value: 120,
    id: "itemThree120",
    idItem: "itemSecond41",
  },
  {
    label: "متعلقات گیربکس",
    value: 121,
    id: "itemThree121",
    idItem: "itemSecond41",
  },
  {
    label: "سیستم کولینگ",
    value: 122,
    id: "itemThree122",
    idItem: "itemSecond42",
  },
  {
    label: "فیلتراسیون",
    value: 123,
    id: "itemThree123",
    idItem: "itemSecond42",
  },
  {
    label: "متعلقات موتور",
    value: 124,
    id: "itemThree124",
    idItem: "itemSecond42",
  },
  {
    label: " موتور",
    value: 125,
    id: "itemThree125",
    idItem: "itemSecond42",
  },

  {
    label: "DPF و متعلقات",
    value: 126,
    id: "itemThree126",
    idItem: "itemSecond43",
  },
  {
    label: "SCR و متعلقات",
    value: 127,
    id: "itemThree127",
    idItem: "itemSecond43",
  },
  {
    label: "اگزوز",
    value: 128,
    id: "itemThree128",
    idItem: "itemSecond43",
  },
  {
    label: "مخازن و سوخت",
    value: 129,
    id: "itemThree129",
    idItem: "itemSecond43",
  },
  {
    label: "بیرون اتاق",
    value: 130,
    id: "itemThree130",
    idItem: "itemSecond44",
  },
  {
    label: "داخل اتاق",
    value: 131,
    id: "itemThree131",
    idItem: "itemSecond44",
  },
  {
    label: "قطعات منفصل بدنه",
    value: 132,
    id: "itemThree132",
    idItem: "itemSecond44",
  },
  {
    label: "الکترونیک ترمز",
    value: 133,
    id: "itemThree133",
    idItem: "itemSecond45",
  },
  {
    label: "مدار ترمز",
    value: 134,
    id: "itemThree134",
    idItem: "itemSecond45",
  },
  {
    label: "مکانیک ترمز",
    value: 135,
    id: "itemThree135",
    idItem: "itemSecond45",
  },
  {
    label: "رام ها و مجموعه قطعات شاسی",
    value: 136,
    id: "itemThree136",
    idItem: "itemSecond46",
  },
  {
    label: "متعلقات سیستم تعلیق",
    value: 137,
    id: "itemThree137",
    idItem: "itemSecond46",
  },
  {
    label: "جعبه فرمان",
    value: 138,
    id: "itemThree138",
    idItem: "itemSecond47",
  },
  {
    label: "ستون فرمان",
    value: 139,
    id: "itemThree139",
    idItem: "itemSecond47",
  },
  {
    label: "مدار هیدرولیک",
    value: 140,
    id: "itemThree140",
    idItem: "itemSecond47",
  },
  {
    label: "شیفتینگ",
    value: 141,
    id: "itemThree141",
    idItem: "itemSecond48",
  },
  {
    label: "گیربکس",
    value: 142,
    id: "itemThree142",
    idItem: "itemSecond48",
  },
  {
    label: "متعلقات گیربکس",
    value: 143,
    id: "itemThree143",
    idItem: "itemSecond48",
  },
  {
    label: "سیستم کولینگ",
    value: 144,
    id: "itemThree144",
    idItem: "itemSecond49",
  },
  {
    label: "فیلتراسیون",
    value: 145,
    id: "itemThree145",
    idItem: "itemSecond49",
  },
  {
    label: "متعلقات موتور",
    value: 146,
    id: "itemThree146",
    idItem: "itemSecond49",
  },
  {
    label: " موتور",
    value: 147,
    id: "itemThree147",
    idItem: "itemSecond49",
  },

  {
    label: "DPF و متعلقات",
    value: 148,
    id: "itemThree148",
    idItem: "itemSecond50",
  },
  {
    label: "SCR و متعلقات",
    value: 149,
    id: "itemThree149",
    idItem: "itemSecond50",
  },
  {
    label: "اگزوز",
    value: 150,
    id: "itemThree150",
    idItem: "itemSecond50",
  },
  {
    label: "مخازن و سوخت",
    value: 151,
    id: "itemThree151",
    idItem: "itemSecond50",
  },
  {
    label: "بیرون اتاق",
    value: 152,
    id: "itemThree152",
    idItem: "itemSecond51",
  },
  {
    label: "داخل اتاق",
    value: 153,
    id: "itemThree153",
    idItem: "itemSecond51",
  },
  {
    label: "قطعات منفصل بدنه",
    value: 154,
    id: "itemThree154",
    idItem: "itemSecond51",
  },
  {
    label: "الکترونیک ترمز",
    value: 155,
    id: "itemThree155",
    idItem: "itemSecond52",
  },
  {
    label: "مدار ترمز",
    value: 156,
    id: "itemThree156",
    idItem: "itemSecond52",
  },
  {
    label: "مکانیک ترمز",
    value: 157,
    id: "itemThree157",
    idItem: "itemSecond52",
  },
  {
    label: "رام ها و مجموعه قطعات شاسی",
    value: 158,
    id: "itemThree158",
    idItem: "itemSecond53",
  },
  {
    label: "متعلقات سیستم تعلیق",
    value: 159,
    id: "itemThree159",
    idItem: "itemSecond53",
  },
  {
    label: "جعبه فرمان",
    value: 160,
    id: "itemThree160",
    idItem: "itemSecond54",
  },
  {
    label: "ستون فرمان",
    value: 161,
    id: "itemThree161",
    idItem: "itemSecond54",
  },
  {
    label: "مدار هیدرولیک",
    value: 162,
    id: "itemThree162",
    idItem: "itemSecond54",
  },
  {
    label: "شیفتینگ",
    value: 163,
    id: "itemThree163",
    idItem: "itemSecond55",
  },
  {
    label: "گیربکس",
    value: 164,
    id: "itemThree164",
    idItem: "itemSecond55",
  },
  {
    label: "متعلقات گیربکس",
    value: 165,
    id: "itemThree165",
    idItem: "itemSecond55",
  },
  {
    label: "سیستم کولینگ",
    value: 166,
    id: "itemThree166",
    idItem: "itemSecond56",
  },
  {
    label: "فیلتراسیون",
    value: 167,
    id: "itemThree167",
    idItem: "itemSecond56",
  },
  {
    label: "متعلقات موتور",
    value: 168,
    id: "itemThree168",
    idItem: "itemSecond56",
  },
  {
    label: " موتور",
    value: 169,
    id: "itemThree169",
    idItem: "itemSecond56",
  },
];

// ************************************************four******************************************************
export const four = [
  {
    label: "ABS",
    value: 1,
    id: "itemFour1",
    idItem: "itemThree8",
  },
  {
    label: "EBS",
    value: 2,
    id: "itemFour2",
    idItem: "itemThree8",
  },
  {
    label: "EBP",
    value: 3,
    id: "itemFour3",
    idItem: "itemThree8",
  },
  {
    label: "SBC",
    value: 4,
    id: "itemFour4",
    idItem: "itemThree8",
  },
  {
    label: "ABS",
    value: 5,
    id: "itemFour5",
    idItem: "itemThree811",
  },
  {
    label: "EBS",
    value: 6,
    id: "itemFour5",
    idItem: "itemThree811",
  },
  {
    label: "EBP",
    value: 7,
    id: "itemFour7",
    idItem: "itemThree811",
  },
  {
    label: "SBC",
    value: 8,
    id: "itemFour8",
    idItem: "itemThree811",
  },
  {
    label: "ABS",
    value: 9,
    id: "itemFour9",
    idItem: "itemThree815",
  },
  {
    label: "EBS",
    value: 10,
    id: "itemFour10",
    idItem: "itemThree815",
  },
  {
    label: "EBP",
    value: 11,
    id: "itemFour11",
    idItem: "itemThree815",
  },
  {
    label: "SBC",
    value: 12,
    id: "itemFour12",
    idItem: "itemThree815",
  },
  {
    label: "ABS",
    value: 13,
    id: "itemFour13",
    idItem: "itemThree817",
  },
  {
    label: "EBS",
    value: 14,
    id: "itemFour14",
    idItem: "itemThree817",
  },
  {
    label: "EBP",
    value: 15,
    id: "itemFour15",
    idItem: "itemThree817",
  },
  {
    label: "SBC",
    value: 16,
    id: "itemFour16",
    idItem: "itemThree817",
  },
  {
    label: "مدار پنوماتیک",
    value: 17,
    id: "itemFour17",
    idItem: "itemThree9",
  },
  {
    label: "مدار هیدرولیک",
    value: 18,
    id: "itemFour18",
    idItem: "itemThree9",
  },
  {
    label: "مدار پنوماتیک",
    value: 19,
    id: "itemFour19",
    idItem: "itemThree812",
  },
  {
    label: "مدار هیدرولیک",
    value: 20,
    id: "itemFour20",
    idItem: "itemThree812",
  },
  {
    label: "مدار پنوماتیک",
    value: 21,
    id: "itemFour22",
    idItem: "itemThree818",
  },
  {
    label: "مدار هیدرولیک",
    value: 23,
    id: "itemFour23",
    idItem: "itemThree818",
  },
  {
    label: "ترمز دیسکی",
    value: 24,
    id: "itemFour24",
    idItem: "itemThree10",
  },
  {
    label: "ترمز کاسه‌ای",
    value: 25,
    id: "itemFour25",
    idItem: "itemThree10",
  },
  {
    label: "ترمز دیسکی",
    value: 26,
    id: "itemFour26",
    idItem: "itemThree813",
  },
  {
    label: "ترمز کاسه‌ای",
    value: 27,
    id: "itemFour27",
    idItem: "itemThree813",
  },
  {
    label: "ترمز دیسکی",
    value: 28,
    id: "itemFour28",
    idItem: "itemThree819",
  },
  {
    label: "ترمز کاسه‌ای",
    value: 29,
    id: "itemFour29",
    idItem: "itemThree819",
  },

  {
    label: "ABS",
    value: 30,
    id: "itemFour30",
    idItem: "itemThree89",
  },
  {
    label: "EBS",
    value: 31,
    id: "itemFour31",
    idItem: "itemThree89",
  },
  {
    label: "EBP",
    value: 32,
    id: "itemFour32",
    idItem: "itemThree89",
  },
  {
    label: "SBC",
    value: 33,
    id: "itemFour33",
    idItem: "itemThree89",
  },

  {
    label: "ABS",
    value: 34,
    id: "itemFour34",
    idItem: "itemThree111",
  },
  {
    label: "EBS",
    value: 35,
    id: "itemFour35",
    idItem: "itemThree111",
  },
  {
    label: "EBP",
    value: 36,
    id: "itemFour36",
    idItem: "itemThree111",
  },
  {
    label: "SBC",
    value: 37,
    id: "itemFour37",
    idItem: "itemThree111",
  },

  {
    label: "ABS",
    value: 38,
    id: "itemFour38",
    idItem: "itemThree133",
  },
  {
    label: "EBS",
    value: 39,
    id: "itemFour39",
    idItem: "itemThree133",
  },
  {
    label: "EBP",
    value: 40,
    id: "itemFour40",
    idItem: "itemThree133",
  },
  {
    label: "SBC",
    value: 41,
    id: "itemFour41",
    idItem: "itemThree133",
  },

  {
    label: "ABS",
    value: 42,
    id: "itemFour42",
    idItem: "itemThree155",
  },
  {
    label: "EBS",
    value: 43,
    id: "itemFour43",
    idItem: "itemThree155",
  },
  {
    label: "EBP",
    value: 44,
    id: "itemFour44",
    idItem: "itemThree155",
  },
  {
    label: "SBC",
    value: 45,
    id: "itemFour45",
    idItem: "itemThree155",
  },

  {
    label: "مدار پنوماتیک",
    value: 46,
    id: "itemFour46",
    idItem: "itemThree90",
  },
  {
    label: "مدار هیدرولیک",
    value: 47,
    id: "itemFour47",
    idItem: "itemThree90",
  },

  {
    label: "مدار پنوماتیک",
    value: 48,
    id: "itemFour48",
    idItem: "itemThree112",
  },
  {
    label: "مدار هیدرولیک",
    value: 49,
    id: "itemFour49",
    idItem: "itemThree112",
  },

  {
    label: "مدار پنوماتیک",
    value: 50,
    id: "itemFour50",
    idItem: "itemThree134",
  },
  {
    label: "مدار هیدرولیک",
    value: 51,
    id: "itemFour51",
    idItem: "itemThree134",
  },
  {
    label: "مدار پنوماتیک",
    value: 52,
    id: "itemFour52",
    idItem: "itemThree156",
  },
  {
    label: "مدار هیدرولیک",
    value: 53,
    id: "itemFour53",
    idItem: "itemThree156",
  },

  {
    label: "ترمز دیسکی",
    value: 54,
    id: "itemFour54",
    idItem: "itemThree91",
  },
  {
    label: "ترمز کاسه‌ای",
    value: 55,
    id: "itemFour55",
    idItem: "itemThree91",
  },
  {
    label: "ترمز دیسکی",
    value: 56,
    id: "itemFour56",
    idItem: "itemThree113",
  },
  {
    label: "ترمز کاسه‌ای",
    value: 57,
    id: "itemFour57",
    idItem: "itemThree113",
  },
  {
    label: "ترمز دیسکی",
    value: 58,
    id: "itemFour58",
    idItem: "itemThree135",
  },
  {
    label: "ترمز کاسه‌ای",
    value: 59,
    id: "itemFour59",
    idItem: "itemThree135",
  },
  {
    label: "ترمز دیسکی",
    value: 60,
    id: "itemFour60",
    idItem: "itemThree157",
  },
  {
    label: "ترمز کاسه‌ای",
    value: 61,
    id: "itemFour61",
    idItem: "itemThree157",
  },
];

// **********************************************five***********************************************************
export const five = [
  {
    label: "ECU",
    value: 1,
    id: "itemFive1",
    idItem: "itemFour1",
  },
  {
    label: "سنسور چرخ",
    value: 2,
    id: "itemFive2",
    idItem: "itemFour1",
  },
  {
    label: "مدولاتور",
    value: 3,
    id: "itemFive3",
    idItem: "itemFour1",
  },
  {
    label: "ECU",
    value: 4,
    id: "itemFive4",
    idItem: "itemFour5",
  },
  {
    label: "سنسور چرخ",
    value: 5,
    id: "itemFive5",
    idItem: "itemFour5",
  },
  {
    label: "مدولاتور",
    value: 6,
    id: "itemFive6",
    idItem: "itemFour5",
  },
  {
    label: "ECU",
    value: 7,
    id: "itemFive7",
    idItem: "itemFour9",
  },
  {
    label: "سنسور چرخ",
    value: 8,
    id: "itemFive8",
    idItem: "itemFour9",
  },
  {
    label: "مدولاتور",
    value: 9,
    id: "itemFive9",
    idItem: "itemFour9",
  },
  {
    label: "ECU",
    value: 10,
    id: "itemFive10",
    idItem: "itemFour13",
  },
  {
    label: "سنسور چرخ",
    value: 10,
    id: "itemFive10",
    idItem: "itemFour13",
  },
  {
    label: "مدولاتور",
    value: 10,
    id: "itemFive10",
    idItem: "itemFour13",
  },

  {
    label: "آبگیر",
    value: 11,
    id: "itemFive11",
    idItem: "itemFour17",
  },
  {
    label: "پمپ باد",
    value: 12,
    id: "itemFive12",
    idItem: "itemFour17",
  },
  {
    label: "تانک باد",
    value: 13,
    id: "itemFive13",
    idItem: "itemFour17",
  },
  {
    label: " سوپاپ ترمز",
    value: 1452,
    id: "itemFive1352",
    idItem: "itemFour17",
  },
  {
    label: " سوپاپ رله",
    value: 152,
    id: "itemFive152",
    idItem: "itemFour17",
  },
  {
    label: "مدولاتور",
    value: 14,
    id: "itemFive14",
    idItem: "itemFour17",
  },
  {
    label: "ABS پمپ",
    value: 15,
    id: "itemFive15",
    idItem: "itemFour18",
  },
  {
    label: "بوستر خلع",
    value: 16,
    id: "itemFive16",
    idItem: "itemFour18",
  },
  {
    label: "سرو سلیندر",
    value: 17,
    id: "itemFive17",
    idItem: "itemFour18",
  },
  {
    label: "مستر سلیندر",
    value: 18,
    id: "itemFive18",
    idItem: "itemFour18",
  },
  {
    label: "آبگیر",
    value: 19,
    id: "itemFive19",
    idItem: "itemFour19",
  },
  {
    label: "پمپ باد",
    value: 20,
    id: "itemFive20",
    idItem: "itemFour19",
  },
  {
    label: "تانک باد",
    value: 21,
    id: "itemFive21",
    idItem: "itemFour19",
  },
  {
    label: " سوپاپ ترمز",
    value: 2125,
    id: "itemFive21548956",
    idItem: "itemFour19",
  },
  {
    label: " سوپاپ رله",
    value: 215,
    id: "itemFive2148956",
    idItem: "itemFour19",
  },
  {
    label: "مدولاتر ",
    value: 22,
    id: "itemFive22",
    idItem: "itemFour19",
  },
  {
    label: "ABS پمپ",
    value: 23,
    id: "itemFive23",
    idItem: "itemFour20",
  },
  {
    label: "بوستر خلع",
    value: 24,
    id: "itemFive24",
    idItem: "itemFour20",
  },
  {
    label: "سرو سلیندر",
    value: 25,
    id: "itemFive25",
    idItem: "itemFour20",
  },
  {
    label: "مستر سلیندر",
    value: 26,
    id: "itemFive26",
    idItem: "itemFour20",
  },
  {
    label: "آبگیر",
    value: 27,
    id: "itemFive27",
    idItem: "itemFour21",
  },
  {
    label: "پمپ باد",
    value: 28,
    id: "itemFive28",
    idItem: "itemFour21",
  },
  {
    label: "تانک باد",
    value: 29,
    id: "itemFive29",
    idItem: "itemFour21",
  },
  {
    label: " سوپاپ ترمز",
    value: 292,
    id: "itemFive295",
    idItem: "itemFour21",
  },
  {
    label: " سوپاپ رله",
    value: 292,
    id: "itemFive295",
    idItem: "itemFour21",
  },
  {
    label: "مدولاتور ",
    value: 30,
    id: "itemFive30",
    idItem: "itemFour21",
  },
  {
    label: "ABS پمپ",
    value: 31,
    id: "itemFive31",
    idItem: "itemFour22",
  },
  {
    label: "بوستر خلع",
    value: 32,
    id: "itemFive32",
    idItem: "itemFour22",
  },
  {
    label: "سرو سلیندر",
    value: 33,
    id: "itemFive33",
    idItem: "itemFour22",
  },
  {
    label: "مستر سلیندر",
    value: 34,
    id: "itemFive26",
    idItem: "itemFour22",
  },
  {
    label: "آبگیر",
    value: 35,
    id: "itemFive35",
    idItem: "itemFour23",
  },
  {
    label: "پمپ باد",
    value: 36,
    id: "itemFive36",
    idItem: "itemFour23",
  },
  {
    label: "تانک باد",
    value: 37,
    id: "itemFive37",
    idItem: "itemFour23",
  },
  {
    label: " سوپاپ ترمز",
    value: 3587,
    id: "itemFive354857",
    idItem: "itemFour23",
  },
  {
    label: " سوپاپ رله",
    value: 387,
    id: "itemFive35857",
    idItem: "itemFour23",
  },
  {
    label: "مدولاتور ",
    value: 38,
    id: "itemFive38",
    idItem: "itemFour23",
  },

  {
    label: "ABS پمپ",
    value: 39,
    id: "itemFive39",
    idItem: "itemFour24",
  },
  {
    label: "بوستر خلع",
    value: 40,
    id: "itemFive40",
    idItem: "itemFour24",
  },
  {
    label: "سرو سلیندر",
    value: 41,
    id: "itemFive41",
    idItem: "itemFour24",
  },
  {
    label: "مستر سلیندر",
    value: 42,
    id: "itemFive42",
    idItem: "itemFour24",
  },

  {
    label: "ECU",
    value: 43,
    id: "itemFive43",
    idItem: "itemFour30",
  },
  {
    label: "سنسور چرخ",
    value: 44,
    id: "itemFive44",
    idItem: "itemFour30",
  },
  {
    label: "مدولاتور",
    value: 45,
    id: "itemFive45",
    idItem: "itemFour30",
  },

  {
    label: "ECU",
    value: 46,
    id: "itemFive46",
    idItem: "itemFour34",
  },
  {
    label: "سنسور چرخ",
    value: 47,
    id: "itemFive47",
    idItem: "itemFour34",
  },
  {
    label: "مدولاتور",
    value: 48,
    id: "itemFive48",
    idItem: "itemFour34",
  },
  {
    label: "ECU",
    value: 49,
    id: "itemFive49",
    idItem: "itemFour38",
  },
  {
    label: "سنسور چرخ",
    value: 50,
    id: "itemFive50",
    idItem: "itemFour38",
  },
  {
    label: "مدولاتور",
    value: 51,
    id: "itemFive51",
    idItem: "itemFour38",
  },
  {
    label: "ECU",
    value: 52,
    id: "itemFive52",
    idItem: "itemFour42",
  },
  {
    label: "سنسور چرخ",
    value: 53,
    id: "itemFive53",
    idItem: "itemFour42",
  },
  {
    label: "مدولاتور",
    value: 54,
    id: "itemFive54",
    idItem: "itemFour42",
  },

  {
    label: "آبگیر",
    value: 55,
    id: "itemFive55",
    idItem: "itemFour46",
  },
  {
    label: "پمپ باد",
    value: 56,
    id: "itemFive56",
    idItem: "itemFour46",
  },
  {
    label: "تانک باد",
    value: 57,
    id: "itemFive57",
    idItem: "itemFour46",
  },
  {
    label: " سوپاپ ترمز",
    value: 58,
    id: "itemFive58",
    idItem: "itemFour46",
  },
  {
    label: " سوپاپ رله",
    value: 59,
    id: "itemFive59",
    idItem: "itemFour46",
  },
  {
    label: "مدولاتور ",
    value: 60,
    id: "itemFive60",
    idItem: "itemFour46",
  },

  {
    label: "ABS پمپ",
    value: 61,
    id: "itemFive61",
    idItem: "itemFour47",
  },
  {
    label: "بوستر خلع",
    value: 62,
    id: "itemFive62",
    idItem: "itemFour47",
  },
  {
    label: "سرو سلیندر",
    value: 63,
    id: "itemFive63",
    idItem: "itemFour47",
  },
  {
    label: "مستر سلیندر",
    value: 64,
    id: "itemFive64",
    idItem: "itemFour47",
  },

  {
    label: "آبگیر",
    value: 65,
    id: "itemFive65",
    idItem: "itemFour48",
  },
  {
    label: "پمپ باد",
    value: 66,
    id: "itemFive66",
    idItem: "itemFour48",
  },
  {
    label: "تانک باد",
    value: 67,
    id: "itemFive67",
    idItem: "itemFour48",
  },
  {
    label: " سوپاپ ترمز",
    value: 68,
    id: "itemFive68",
    idItem: "itemFour48",
  },
  {
    label: " سوپاپ رله",
    value: 69,
    id: "itemFive69",
    idItem: "itemFour48",
  },
  {
    label: "مدولاتور ",
    value: 70,
    id: "itemFive70",
    idItem: "itemFour48",
  },

  {
    label: "ABS پمپ",
    value: 71,
    id: "itemFive71",
    idItem: "itemFour49",
  },
  {
    label: "بوستر خلع",
    value: 72,
    id: "itemFive72",
    idItem: "itemFour49",
  },
  {
    label: "سرو سلیندر",
    value: 73,
    id: "itemFive73",
    idItem: "itemFour49",
  },
  {
    label: "مستر سلیندر",
    value: 74,
    id: "itemFive74",
    idItem: "itemFour49",
  },

  {
    label: "آبگیر",
    value: 75,
    id: "itemFive75",
    idItem: "itemFour50",
  },
  {
    label: "پمپ باد",
    value: 76,
    id: "itemFive76",
    idItem: "itemFour50",
  },
  {
    label: "تانک باد",
    value: 77,
    id: "itemFive77",
    idItem: "itemFour50",
  },
  {
    label: " سوپاپ ترمز",
    value: 78,
    id: "itemFive78",
    idItem: "itemFour50",
  },
  {
    label: " سوپاپ رله",
    value: 79,
    id: "itemFive79",
    idItem: "itemFour50",
  },
  {
    label: "مدولاتور ",
    value: 80,
    id: "itemFive80",
    idItem: "itemFour50",
  },

  {
    label: "ABS پمپ",
    value: 81,
    id: "itemFive81",
    idItem: "itemFour51",
  },
  {
    label: "بوستر خلع",
    value: 82,
    id: "itemFive82",
    idItem: "itemFour51",
  },
  {
    label: "سرو سلیندر",
    value: 83,
    id: "itemFive83",
    idItem: "itemFour51",
  },
  {
    label: "مستر سلیندر",
    value: 84,
    id: "itemFive84",
    idItem: "itemFour51",
  },

  {
    label: "آبگیر",
    value: 85,
    id: "itemFive85",
    idItem: "itemFour52",
  },
  {
    label: "پمپ باد",
    value: 86,
    id: "itemFive86",
    idItem: "itemFour52",
  },
  {
    label: "تانک باد",
    value: 87,
    id: "itemFive87",
    idItem: "itemFour52",
  },
  {
    label: " سوپاپ ترمز",
    value: 88,
    id: "itemFive88",
    idItem: "itemFour52",
  },
  {
    label: " سوپاپ رله",
    value: 89,
    id: "itemFive89",
    idItem: "itemFour52",
  },
  {
    label: "مدولاتور ",
    value: 90,
    id: "itemFive90",
    idItem: "itemFour52",
  },

  {
    label: "ABS پمپ",
    value: 91,
    id: "itemFive91",
    idItem: "itemFour53",
  },
  {
    label: "بوستر خلع",
    value: 92,
    id: "itemFive92",
    idItem: "itemFour53",
  },
  {
    label: "سرو سلیندر",
    value: 93,
    id: "itemFive93",
    idItem: "itemFour53",
  },
  {
    label: "مستر سلیندر",
    value: 94,
    id: "itemFive94",
    idItem: "itemFour53",
  },
];
